### PR TITLE
add lock args

### PR DESCRIPTION
**Pull request by paul-krohn**
and fix `with app.context():` as used in krux-log-archiver

### CODE REVIEW

**Comment by hanpeter** [comment]
Can we either comment or log that `raise_critical_error()` is now deprecated and should be replaced by `context()`?

Otherwise, LGTM.

**Comment by paul-krohn** [comment]
I am agnostic on whether `raise_critical_error()` is deprecated but it seems to me that it is not, there may be cases where you want to exit non-zero and at the moment `context()` does not provide that?

**Comment by hanpeter** [comment]
If I am reading the code correctly, I believe that the application will hit `raise` on line 270 and exit with 1. `self.exit()` on line 275 will be only hit on success case. If you want a specific exit code, then yes, this does not support that.

More so, I really do not like how `raise_critical_error()` raises its own error. This makes all stack traces to stop at this function, making the stack traces useless. I am fine if we decide to fix `raise_critical_error()` instead of deprecating it, but that would be outside the scope of this PR.

**Comment by plathrop** [comment]
I don't agree that it makes the stack traces useless. You have to read the full stack trace, just like you should be doing ANY time you get a stack trace. It's actually the *exception* when a stack trace ends in the actual source of the error.

I don't believe we should deprecate `raise_critical_error`. I think that `context` should be the recommended and default way, but there are still use cases for finer-grained control of application exit.

**Pull request merged**
